#NumPy

### Importing

In [0]:
import numpy as np

### Creating array

In [0]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype="int32")

arr1

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int32)

### get datatype of array
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string

In [0]:
arr1.dtype

dtype('int32')

### Dimentions

In [0]:
arr1.ndim

1

In [0]:
D0 = np.array("10")
D1 = np.array(["10", "8", "6"])
D2 = np.array([["10", "8", "6"],["10", "8", "6"]])
D3 = np.array([[["10", "8", "6"],["10", "8", "6"]], [["10", "8", "6"],["10", "8", "6"]]])

print(D0.ndim)
print(D1.ndim)
print(D2.ndim)
print(D3.ndim)

0
1
2
3

In [0]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10], ndmin=2)
print(arr2)

[[ 1 2 3 4 5 6 7 8 9 10]]

In [0]:
arr3 = np.array(
  [
    [
      [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ]
    ],
    [
      [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ]
    ]
  ])
print(arr3.ndim)

4

### Get Values

In [0]:
print(arr1[3:7])
print(arr1[::3])
print(arr1[-3:-7:-2])

[4 5 6 7]
[ 1 4 7 10]
[8 6]

In [0]:
D2[0,1:3]

array(['8', '6'], dtype='<U2')

In [0]:
D3[0,1,1]

'8'

# Mathematics

In [0]:
# x = [1,2,3]
# x+1

print("actual:", arr3)
print("+:", arr3+2)
print("-:", arr3-2)
print("*:", arr3*2)
print("/:", arr3/2)
print("%:", arr3%2)
print("^2:", arr3**2)

actual: [[[[1 2 3]
 [4 5 6]
 [7 8 9]]]


 [[[1 2 3]
 [4 5 6]
 [7 8 9]]]]
+: [[[[ 3 4 5]
 [ 6 7 8]
 [ 9 10 11]]]


 [[[ 3 4 5]
 [ 6 7 8]
 [ 9 10 11]]]]
-: [[[[-1 0 1]
 [ 2 3 4]
 [ 5 6 7]]]


 [[[-1 0 1]
 [ 2 3 4]
 [ 5 6 7]]]]
*: [[[[ 2 4 6]
 [ 8 10 12]
 [14 16 18]]]


 [[[ 2 4 6]
 [ 8 10 12]
 [14 16 18]]]]
/:

[[[[0.5 1. 1.5]
 [2. 2.5 3. ]
 [3.5 4. 4.5]]]


 [[[0.5 1. 1.5]
 [2. 2.5 3. ]
 [3.5 4. 4.5]]]]
%: [[[[1 0 1]
 [0 1 0]
 [1 0 1]]]


 [[[1 0 1]
 [0 1 0]
 [1 0 1]]]]
^2: [[[[ 1 4 9]
 [16 25 36]
 [49 64 81]]]


 [[[ 1 4 9]
 [16 25 36]
 [49 64 81]]]]

# Shape

In [0]:
arr3.shape

(2, 1, 3, 3)

In [0]:
l_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(l_arr)
print(l_arr.shape)

l_arr2 = l_arr.reshape(4,3)
print(l_arr2)

[ 1 2 3 4 5 6 7 8 9 10 11 12]
(12,)
[[ 1 2 3]
 [ 4 5 6]
 [ 7 8 9]
 [10 11 12]]

# Randomes

In [0]:
a1 = np.zeros([3,3])
print(a1)

a2 = np.ones([3,3])
print(a2)

a3 = np.full([3,3], 10)
print(a3)

a4 = np.identity(3)
print(a4)

a5 = np.random.rand(3, 3)
print(a5)

a6 = np.random.randint(1, 10, [3,3])
print(a6)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.47253807 0.44442031 0.72123515]
 [0.20828903 0.54706465 0.69859795]
 [0.56160246 0.67643473 0.09317741]]
[[3 3 9]
 [5 3 9]
 [2 2 3]]

In [0]:
a6 + a4
a6.size

9

In [0]:
a6_d = a6
print(a6)
print(a6_d)

a6_d[1,1] = 10

print(a6_d)
print(a6)

a6_c = a6.copy()
a6_c[1,1] = 20

print(a6_c)
print(a6)


[[3 3 9]
 [5 3 9]
 [2 2 3]]
[[3 3 9]
 [5 3 9]
 [2 2 3]]
[[ 3 3 9]
 [ 5 10 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 10 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 20 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 10 9]
 [ 2 2 3]]

In [0]:
a6_d = a6.view()
print(a6)
print(a6_d)
print("=" * 20)
a6_d[1,1] = 15

print(a6_d)
print(a6)
print("=" * 20)
a6[1,1] = 20

print(a6_d)
print(a6)


[[ 3 3 9]
 [ 5 10 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 10 9]
 [ 2 2 3]]
====================
[[ 3 3 9]
 [ 5 15 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 15 9]
 [ 2 2 3]]
====================
[[ 3 3 9]
 [ 5 20 9]
 [ 2 2 3]]
[[ 3 3 9]
 [ 5 20 9]
 [ 2 2 3]]

In [0]:
a7 = np.random.randint(1, 10, [3,3,3])
print(a7)

[[[1 8 4]
 [6 5 8]
 [3 8 4]]

 [[5 2 1]
 [3 1 2]
 [5 1 1]]

 [[5 8 3]
 [5 8 9]
 [1 5 4]]]

In [0]:
print(D1)

for item in D1:
  print(item)
  
print("=" * 20)
 
# for pm in a7:
#   for cm in pm:
#     for item in cm:
#       print(item)
      
for cm in a7[1,:]:
  for item in cm:
    print(item)
    
print(a7[1,1:2, 1:2])


['10' '8' '6']
10
8
6
====================
5
2
1
3
1
2
5
1
1
[[1]]

In [0]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[4, 5, 6], [1, 2, 3]])

arr = np.concatenate((arr1, arr2))
print(arr)

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]
[[1 2 3 4 5 6]
 [4 5 6 1 2 3]]

In [0]:
arr1 = np.array([3, 2,  5,4,1, 6])
print(arr1)

arr2 = np.array_split(arr1,3)
print(arr2)

print(np.where(arr1 == 4))

print(np.sort(arr1))

print(arr1[arr1%2 == 1])

print(arr1[arr1 >=5])

[3 2 5 4 1 6]
[array([3, 2]), array([5, 4]), array([1, 6])]
(array([3]),)
[1 2 3 4 5 6]
[3 5 1]
[5 6]

# Task

In [0]:
output = np.array([
  [1,1,1,1,1],
  [1,0,0,0,1],
  [1,0,10,0,1],
  [1,0,0,0,1],
  [1,1,1,1,1]
])
output

array([[ 1, 1, 1, 1, 1],
 [ 1, 0, 0, 0, 1],
 [ 1, 0, 10, 0, 1],
 [ 1, 0, 0, 0, 1],
 [ 1, 1, 1, 1, 1]])

In [0]:
grid = np.ones([5,5])
# print(grid)
ch_grid = np.zeros([3,3])
# print(ch_grid)
ch_grid[1,1] = 10
# print(ch_grid)
grid[1:-1, 1:-1] = ch_grid
print(grid)

[[ 1. 1. 1. 1. 1.]
 [ 1. 0. 0. 0. 1.]
 [ 1. 0. 10. 0. 1.]
 [ 1. 0. 0. 0. 1.]
 [ 1. 1. 1. 1. 1.]]